language: go

go:
  - 1.7

before_install:
  - sudo apt-get -qq update

install:
  - go get github.com/Masterminds/glide

script:
  - go get -v ./...
  - go test $(glide novendor)

# Sudo is required for docker
sudo: required

# Enable docker
services:
  - docker

# In Travis, we need to bind to 127.0.0.1 in order to get a working connection. This environment variable
# tells dockertest to do that.
env:
  - DOCKERTEST_BIND_LOCALHOST=true

