###
# Copyright (c) Mainflux ad Nodesign
#
# WeIO Cloud is licensed under an Apache license, version 2.0 license.
# All rights not explicitly granted in the Apache license, version 2.0 are reserved.
# See the included LICENSE file for more details.
###

###
# MongoDB
###
mongo:
  image: mongo:latest
  ports:
    - "27017:27017"
    - "28017:28017"
  container_name: mainflux-mongodb
  command: --smallfiles --nojournal

###
# WeIO Cloud Server
###
mainflux-core:
  image: nodesign/weio-cloud:latest
  container_name: weio-cloud
  links:
    - mongo
  ports:
    - "9900:9900"
